OK_MSG = \x1b[32m ✔\x1b[0m

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

format:
	@echo -n "==> Checking that code is autoformatted with black..."
	@black --check --quiet .
	@echo -e "$(OK_MSG)"