_target_: adamantium.models.hf_module.HFLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: timm.create_model
  model_name: "resnet18"
  in_chans: 3
  pretrained: True
  num_classes: 10