_target_: adamantium.models.vit_module.VitLitModule

num_classes: 1000
in_channels: 3
img_size: 32
patch_size: 4
emb_size: 64
depth: 6

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10