# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10.yaml
  - model: hf.yaml
  - paths: default.yaml
  - trainer: default.yaml

  - experiment: null

# task name, determines output directory path
task_name: "test"

# set False to skip model training
train: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: ${paths.ckpt_dir}

# seed for random number generators in pytorch, numpy and python.random
seed: 0