# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - model: vit.yaml
  - paths: default.yaml

  - experiment: null

# task name, determines output directory path
task_name: "infer"

# set False to skip model training
train: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: ${paths.ckpt_dir}

# simply provide image path to infer
image_path: ${paths.data_dir}/PetImages_split/test/Dog/1.jpg

# seed for random number generators in pytorch, numpy and python.random
seed: 0